### ISSUE TITLE
After installing an extension line not highlighted and ext. server crash

### ISSUE THREAD

**Issue by crystalfp** [Gruntfuggly/todo-tree#113]
I use VSC 1.30.2 on Windows 10 64bits.
Installed and disinstalled Material Theme and Material Icons. Now TodoTree is not highlighting the corresponding comment in the source file (as done before). Even worse, the Extension Host crashes when returning to a source code editor leaving this in the developer window:

![annotation 2019-01-11 135917](https://user-images.githubusercontent.com/865866/51035948-f07fa980-15ab-11e9-928c-a498b9e967c2.jpg)

Here is another instance after disabling/re-enabling todo-tree:
```
[Extension Host] debugger listening on port 43509
log.ts:157  INFO no standard startup: not a new window
extensionHost.ts:235 Extension Host
extensionHost.ts:236 Debugger listening on ws://127.0.0.1:43509/aa650848-a075-4cfe-ab6f-5fc01c7d0506
For help see https://nodejs.org/en/docs/inspector

console.ts:134 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
t.log @ console.ts:134
console.ts:134 [Extension Host] "live-sass-compiler" is now actived! Go and Debug :P 
console.ts:134 [Extension Host] No editors associated with document: c:\Users\Mario Valle\AppData\Roaming\Code\User\settings.json
t.log @ console.ts:134
extensionService.ts:165 Extension host terminated unexpectedly. Code:  7  Signal:  null
t._onExtensionHostCrashed @ extensionService.ts:165
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:40
extensionHost.ts:235 Extension Host
extensionHost.ts:236 C:\Users\Mario Valle\.vscode\extensions\ritwickdey.live-sass-3.0.0\node_modules\sasslib\sass.sync.js:61
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof imp

TypeError: Cannot read property 'replace' of undefined
	at Object.hexToRgba (C:\Users\Mario Valle\.vscode\extensions\gruntfuggly.todo-tree-0.0.113\utils.js:26:15)
	at getDecoration (C:\Users\Mario Valle\.vscode\extensions\gruntfuggly.todo-tree-0.0.113\highlights.js:113:35)
	at C:\Users\Mario Valle\.vscode\extensions\gruntfuggly.todo-tree-0.0.113\highlights.js:309:30
	at Array.forEach (<anonymous>)
	at Timeout.highlight [as _onTimeout] (C:\Users\Mario Valle\.vscode\extensions\gruntfuggly.todo-tree-0.0.113\highlights.js:307:43)
	at ontimeout (timers.js:479:15)
	at tryOnTimeout (timers.js:310:5)
	at Timer.listOnTimeout (timers.js:270:5)
```
Here are the todo-tree settings:
```
    "todo-tree.expanded": true,
    "todo-tree.tags": [
        "TODO",
        "FIXME",
        "TEST",
        ">>>",
        ">>",
        ">"
    ],
    "todo-tree.showTagsFromOpenFilesOnly": true,
    "todo-tree.autoRefresh": true,
    "todo-tree.defaultHighlight": {
        "foreground": "green",
        "type": "line"
    },
    "todo-tree.customHighlight": {
        "TODO": {
            "foreground": "magenta"
        },
        "FIXME": {
            "foreground": "red"
        },
        "TEST": {
            "foreground": "cyan"
        },
        ">": {
            "foreground": "yellow"
        },
        ">>": {
            "foreground": "blue"
        },
        ">>>": {
            "foreground": "grey"
        }
    },
    "todo-tree.regex": "((//|# |<!--|;|/\\* |^)\\s*($TAGS)|^\\s*- \\[ \\])",
    "todo-tree.flat": true,
    "todo-tree.highlightDelay": 250,
    "todo-tree.excludeGlobs": [
        "**/libs",
        "**/node_modules"
    ],
    "todo-tree.showInExplorer": false,
```

Thanks for your time!
mario

**Comment by crystalfp** [comment]
Disabling all extensions and re-enabling only todo-tree does not crashes the Extension Host, but the same error appears in the log window:
![annotation 2019-01-11 144550](https://user-images.githubusercontent.com/865866/51037155-bb755600-15af-11e9-8dad-7f069ff75432.jpg)

And again the lines are not highlighted.
Thanks for your help!
mario

**Comment by crystalfp** [comment]
Deleted VSC, deleted all extensions, reinstalled VSC, reinstalled todo-tree.
Comments with tags in source code are not highlighted.
And the error `[error] Cannot read property 'replace' of undefined:` continues to appear in the log (see above).

**Comment by Gruntfuggly** [comment]
There is a bug where it fails to generate a highlight colour if the configuration is not set up as expected. I'm working on a fix now.

**Comment by Gruntfuggly** [comment]
I've just uploaded a version which checks more carefully and tries to default to a sensible background colour. 

Sorry for the inconvenience - please let me know if there are still any problems.

**Comment by Gruntfuggly** [comment]
It's wierd if it was crashing the extension host - I would just expect to see the error in the console and it should carry on. Maybe something else is happening too?

**Comment by crystalfp** [comment]
OK, fixed also the background by changing defaultHighlight to:
```
    "todo-tree.defaultHighlight": {
        "foreground": "green",
        "background": "transparent",
        "type": "line"
    },
```
Back to normality.
Thanks!
mario

**Comment by Gruntfuggly** [comment]
`transparent` isn't a supported colour - I think it's probably just ignoring it now, which probably works. You could also just remove the `background` property, or also set the `opacity` to 0.

**Comment by crystalfp** [comment]
Change done, work perfectly! Thanks
