### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Sinosaurus** [Gruntfuggly/todo-tree#200]
> extensionHost.ts:202
```
c:\Users\DELL\.vscode\extensions\spook.easysass-0.0.6\lib\sass.sync.js:61
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONM

TypeError: Cannot read property '0' of null
    at new Match (c:\Users\DELL\.vscode\extensions\gruntfuggly.todo-tree-0.0.145\ripgrep.js:213:20)
    at stdout.split.map (c:\Users\DELL\.vscode\extensions\gruntfuggly.todo-tree-0.0.145\ripgrep.js:60:27)
    at Array.map (<anonymous>)
    at formatResults (c:\Users\DELL\.vscode\extensions\gruntfuggly.todo-tree-0.0.145\ripgrep.js:60:10)
    at ChildProcess.<anonymous> (c:\Users\DELL\.vscode\extensions\gruntfuggly.todo-tree-0.0.145\ripgrep.js:183:22)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)

```

close the plugins `todo-tree`, vscode run is ok

**Comment by Gruntfuggly** [comment]
Could you post a copy of your `todo-tree` settings - I can see why that is happening (and I'll fix it ASAP) but I don't understand how it is getting to that situation.

**Comment by JakubKoralewski** [comment]
The same happens for me. Looking in the settings.json I don't find anything that's changed from the default for todo-tree. Should I be looking in the UI settings?

**Comment by Gruntfuggly** [comment]
Do you see anything in the `todo-tree` output channel?

**Comment by JakubKoralewski** [comment]
```
Searching <PATH>...
Command: "f:\PROGRAMY\VS Code\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "<PATH>"
```
The above command displays TODOs inside my files

**Comment by Gruntfuggly** [comment]
Is that all it shows? If not, can you just add a couple of the results shown after.

**Comment by Gruntfuggly** [comment]
Hopefully they should be 

<filename>:<line>:<column>:<text>

If not, that would explain why it's failing.

**Comment by JakubKoralewski** [comment]
```
<PATH>\script.tsx:1:1:// TODO: use webpack instead of parcel
<PATH>\script.tsx:7:1:// FIXME: to stop Parcel clearing console on HMR
<PATH>\script.tsx:48:3:		// TODO: throw error if no file
```
here you go

**Comment by Gruntfuggly** [comment]
I've just published a new version which should handle the situation better. Please let me know if it works for you.

**Comment by JakubKoralewski** [comment]
Seems to work! Thanks for the quick fix.

![image](https://user-images.githubusercontent.com/43069023/64600630-cb9e3900-d3bb-11e9-81f3-95a3ebe70647.png)
