### ISSUE TITLE
ReferenceError: os is not defined

### ISSUE THREAD

**Issue by thalesfsp** [Gruntfuggly/todo-tree#201]
OS: `macOS Mojave 10.14.6`
VS Code:
```
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```
Action: `Extension -> Export Tree`
Error Message: `[2019-09-09 11:07:33.598] [exthost] [error] ReferenceError: os is not defined`
Stack:
```
at exportTree (/Users/USER/.vscode/extensions/gruntfuggly.todo-tree-0.0.145/extension.js:637:66)
at /Users/USER/.vscode/extensions/gruntfuggly.todo-tree-0.0.145/extension.js:785:13
```

**Comment by thalesfsp** [comment]
@Gruntfuggly Fix in PR

**Comment by Gruntfuggly** [comment]
Thanks for the PR - will merge it tomorrow. Not sure how I missed that one!
