### ISSUE TITLE
Running the contributed command: 'todo-tree.refresh' failed.

### ISSUE THREAD

**Issue by PGScully** [Gruntfuggly/todo-tree#440]
This appears to be new in v0.0.197, and only on Windows.

On startup, no todos are found.  Clicking the refresh button gives the following error:

> Running the contributed command: 'todo-tree.refresh' failed.

I also occasionally get the following, and reliably when trying to change todo-tree's settings:

> EINVAL: invalid argument, mkdir '/C:/Users/peter/AppData/Roaming/Code/User/globalStorage/gruntfuggly.todo-tree'

`/C:` should of course be `C:`, and I assume this is the cause of the first error message.

**Comment by Gruntfuggly** [comment]
Please could you open the developer tools and see if there are any errors reported?

**Comment by Gruntfuggly** [comment]
I made a change to replace a deprecated API - maybe it isn't working as I thought it would.

**Comment by PGScully** [comment]
The most recent stack trace is:

Error: EINVAL: invalid argument, mkdir '/C:/Users/peter/AppData/Roaming/Code/User/globalStorage/gruntfuggly.todo-tree'
	at mkdirSync (fs.js:925:3)
	at Object.e.mkdirSync (electron/js2c/asar_bundle.js:5:12016)
	at Object.e.exports.getIcon (c:\Users\peter\.vscode\extensions\gruntfuggly.todo-tree-0.0.197\dist\extension.js:22:12957)
	at t.TreeNodeProvider.getTreeItem (c:\Users\peter\.vscode\extensions\gruntfuggly.todo-tree-0.0.197\dist\extension.js:34:56216)
	at c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:46157
	at Array.map (<anonymous>)
	at g.fetchChildrenNodes (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:46111)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)

And the stack trace previous to it is:

workbench.desktop.main.js:738 Error: Running the contributed command: 'todo-tree.refresh' failed.
	at b._executeContributedCommand (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88571)
	at b.$executeContributedCommand (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88849)
	at p._doInvokeHandler (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10276)
	at p._invokeHandler (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9968)
	at p._receiveRequest (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8638)
	at p._receiveOneMessage (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:7440)
	at c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:5568
	at v.fire (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:29104
	at v.fire (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at t._receiveMessage (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:20765)
	at c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:17659
	at v.fire (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at u.acceptChunk (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12880)
	at c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12228
	at Socket.m (c:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by 9z0** [comment]
Can confirm.
```
EINVAL: invalid argument, mkdir

'/C:/Users/WDAGUtilityAccount/AppData/Roaming/Code/User/globalStorage/gruntfuggly.todo-tree'

00:00:13.858 Attempting to create global storage folder /C:/Users/{snip}/AppData/Roaming/Code/User/globalStorage/gruntfuggly.todo-tree
/C:/Users/{snip}/AppData/Roaming/Code/User/workspaceStorage/{snip}/Gruntfuggly.todo-tree
```

compare with 196:
`00:00:12.984 Writing pattern file:c:\Users\{snip}\AppData\Roaming\Code\User\workspaceStorage\{snip}\Gruntfuggly.todo-tree\{snip}.txt`

Unix and Windows mixed style path. Like @PGScully said maybe it should be `C:` with backslashes OR maybe `/C/` with forward slashes (without the colon).

**Comment by paulirotta** [comment]
Likewise:
`EINVAL: invalid argument, mkdir '/C:/Users/pauli/AppData/Roaming/Code/User/globalStorage/gruntfuggly.todo-tree'`

**Comment by lemonkiller** [comment]
I also had this problem

**Comment by Gruntfuggly** [comment]
For now, please revert to the previous version - I'll try and get this fixed today.

**Comment by Gruntfuggly** [comment]
OK, I've reverted the change which I think caused this. I'll fix it properly when I get some time.

If somebody could confirm it's fixed again, that would be great.

**Comment by TrippyZ** [comment]
This has fixed it for me running 198

**Comment by Gruntfuggly** [comment]
OK - thanks. That's good enough for me. I've got a proper fix for it now too, so it will go into the next release.
