### ISSUE TITLE
Crash since VSCode 1.73.0

### ISSUE THREAD

**Issue by alexgv99** [Gruntfuggly/todo-tree#692]
Since last update, every time I open a file with a TODO annotation the Extension Host crashes.

![image](https://user-images.githubusercontent.com/6002790/200049213-e70895be-f3c3-47c6-ba1d-803a6264c5e2.png)

![image](https://user-images.githubusercontent.com/6002790/200049347-ff19fa69-1862-4183-bd28-7f43843ba643.png)

**Comment by alexgv99** [comment]
Disabling the extension solves the problem.

**Comment by Gruntfuggly** [comment]
Please could you see if there is anything in the developer tools console?

**Comment by alexgv99** [comment]
I've tried... but I reenabled the extension to see if there was something in the devtools console, bu the error has gone. Sorry.

**Comment by WinterPhoenix** [comment]
Bumping this; I'm running into the same issue, but I do have an error in console:

```
TypeError: Class constructor cn cannot be invoked without 'new'
	at p (c:\Users\Winter\.vscode-oss\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:99:15012)
	at c:\Users\Winter\.vscode-oss\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:99:18316
	at Array.forEach (<anonymous>)
	at Timeout.k [as _onTimeout] (c:\Users\Winter\.vscode-oss\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:99:18289)
	at listOnTimeout (node:internal/timers:561:11)
	at process.processTimers (node:internal/timers:502:7)
```

**Comment by Gruntfuggly** [comment]
What version of VSCode are you using and which version of the extension?

**Comment by WinterPhoenix** [comment]
![image](https://user-images.githubusercontent.com/2799393/208837783-736c4f3e-f3b7-437a-956b-f1ab4bc33e86.png)

With the latest version of the extension, `v0.0.215`

**Comment by WinterPhoenix** [comment]
@Gruntfuggly can we reopen this issue so it doesn't get lost?

**Comment by Gruntfuggly** [comment]
The latest version of the extension is 0.0.220 - Please can you try it and see if the issue is still present? 0.0.215 had an issue which was fixed in the next version.
