### ISSUE TITLE
Highlighting stopped working (v0.0.225)

### ISSUE THREAD

**Issue by nunobv** [Gruntfuggly/todo-tree#747]
After installing the extension and customizing the settings, I could successfuly see the code highlighted as intended.

However, the next time I opened vscode, the highlighting functionality stopped working. I can only make it work for the default colour scheme when setting the `"todo-tree.highlights.useColourScheme": false`, otherwise no highlighting is shown.

Am I missing something in the settings or is there a property that is overriding the intended behaviour of the `customHighlight`?

Current settings:
```json
{
    // other vscode settings
    "todo-tree.general.showActivityBarBadge": true,
    "todo-tree.highlights.customHighlight": {
        "BUG": {
            "icon": "bug",
            "foreground": "#ffffffda",
            "background": "#bb0808",
            "iconColour": "#c42a2a"
        },
        "HACK": {
            "icon": "tools"
        },
        "FIX": {
            "icon": "tools",
            "foreground": "#111111",
            "background": "#08a0bb",
            "iconColour": "#08a0bb"
        },
        "XXX": {
            "icon": "x"
        },
        "[ ]": {
            "icon": "issue-draft"
        },
        "DONE": {
            "icon": "issue-closed",
            "background": "#0ea84f",
            "foreground": "#202221",
            "iconColour": "#0ea84f",
            "hideFromStatusBar": true,
            "hideFromActivityBar": true
        },
        "TODO": {
            "iconColour": "#a89e43"
        }
    },
    "todo-tree.highlights.defaultHighlight": {
        "type": "tag"
    },
    "todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "XXX",
        "DONE",
        "FIX"
    ],
    "todo-tree.general.tagGroups": {
        "FIX": [
            "FIX",
            "FIXME"
        ]
    },
    "todo-tree.general.statusBar": "current file",
    "todo-tree.highlights.enabled": true,
    "todo-tree.general.statusBarClickBehaviour": "toggle highlights",
    "todo-tree.tree.showCurrentScanMode": false,
    "todo-tree.tree.buttons.scanMode": true,
    "todo-tree.tree.buttons.expand": false,
    "todo-tree.highlights.useColourScheme": false
}
```

**Comment by nunobv** [comment]
When trying to reload and uninstall/reinstall the extension, I noticed the following message in the hovering window: `This extension has reported 25 uncaught errors`.

After checking `Show Logs...`-> `Extension Host` in the palette, I found the following error message:
```
2023-04-12 00:10:37.250 [error] TypeError: e.toLowerCase is not a function
	at e.exports.convertTransparentColour (c:\Users\XYZ\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:1:2269)
	at c:\Users\XYZ\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:16239
	at v (c:\Users\XYZ\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:16299)
	at c:\Users\XYZ\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:19092
	at Array.forEach (<anonymous>)
	at Timeout.A [as _onTimeout] (c:\Users\XYZ\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:19065)
	at listOnTimeout (node:internal/timers:561:11)
	at process.processTimers (node:internal/timers:502:7)
```

Hopefully this gives a bit more context.

**Comment by Salloom99** [comment]
same here

**Comment by QuantScAv** [comment]
Similar problem

**Comment by nunobv** [comment]
I installed the previous version (**v0.0.224**) and everything seems to be working properly.
Definitely seems to be an issue with the recent update to **v0.0.225**.

*[temporary fix]* For those experiencing the same issue, just right-click on the extension and select `Install another version`.

**Comment by Gruntfuggly** [comment]
Just pushed version 0.0.226 which should hopefully fix this - sorry for the inconvenience!

**Comment by nunobv** [comment]
Seems to be working.
Thanks @Gruntfuggly.
