### ISSUE TITLE
Extension Host crashing after a few seconds

### ISSUE THREAD

**Issue by rol1510** [Gruntfuggly/todo-tree#748]
After a few seconds, the extension host crashes and I'm getting this error:
```
2023-04-12 13:11:07.814 [error] TypeError: e.toLowerCase is not a function
	at e.exports.convertTransparentColour (c:\Users\rol1510\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:1:2269)
	at c:\Users\rol1510\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:16239
	at v (c:\Users\rol1510\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:16299)
	at c:\Users\rol1510\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:19092
	at Array.forEach (<anonymous>)
	at Timeout.A [as _onTimeout] (c:\Users\rol1510\.vscode\extensions\gruntfuggly.todo-tree-0.0.225\dist\extension.js:99:19065)
	at listOnTimeout (node:internal/timers:561:11)
	at process.processTimers (node:internal/timers:502:7)
```

**Comment by trnhattan** [comment]
I think you had the similar issue in #747, check this for the temporary fix :heart:

**Comment by Gruntfuggly** [comment]
Just pushed version 0.0.226 which should hopefully fix this - sorry for the inconvenience!
