### ISSUE TITLE
I'm getting an exception when I try to use this extension with cursorless

### ISSUE THREAD

**Issue by jaresty** [Gruntfuggly/todo-tree#858]
I'm not sure what the issue is, but I did run into an exception when I tried to use cursorless with this extension. Here is a stack trace:

```
 SyntaxError: Invalid flags: ds
	at k (/Users/tkma6d4/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:74341)
	at Array.d (/Users/tkma6d4/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:3580)
	at Object.parse (/Users/tkma6d4/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:71938)
	at r.parse (/Users/tkma6d4/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:1:12754)
	at Object.parse (/Users/tkma6d4/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:415)
	at l (/Users/tkma6d4/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:165)
	at Array.get [as indices] (/Users/tkma6d4/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:2895)
	at iD.run (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:133:100520)
	at predicate (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:133:98074)
	at /Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:133:104145
	at Array.every (<anonymous>)
	at /Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:133:104136
	at Array.filter (<anonymous>)
	at t.matches (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:133:104089)
	at wy.generateScopeCandidates (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:133:34153)
	at generateScopeCandidates.next (<anonymous>)
	at wy.generateScopes (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:133:28877)
	at generateScopes.next (<anonymous>)
	at pP (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:120:6146)
	at u9 (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:148:26958)
	at M2.getScopeSupport (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:148:26705)
	at r (/Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:148:28102)
	at /Users/tkma6d4/.vscode/extensions/pokey.cursorless-0.28.1158/extension.cjs:148:28269
	at Array.map (<anonymous>)
```

Related issue: https://github.com/cursorless-dev/cursorless/issues/2470

**Comment by j-fulbright** [comment]
Related to https://github.com/Gruntfuggly/todo-tree/issues/853

**Comment by boltex** [comment]
I'm also getting 'Invalid flags: dgm' that is breaking my extensions. Similar to this: https://github.com/renpy/vscode-language-renpy/issues/364#issuecomment-1774052287

**Comment by FanaticPythoner** [comment]
@jaresty @j-fulbright @boltex See https://github.com/FanaticPythoner/better-todo-tree ;  should've been fixed a while ago already, and if you encounter (somehow??) that issue still, open an issue there and it gets resolved in days. Tons of improvements also. (Tons of) Various other improvements/bug fixes. The original todo-tree repo is abandoned.
