### ISSUE TITLE
Extension crashes when debugging other extensions

### ISSUE THREAD

**Issue by triztian** [Gruntfuggly/todo-tree#90]
It seems like the extension fails to load when another extension is debugged; it's easy to reproduce, just clone 

 * https://github.com/Microsoft/vscode-go

And run the tests as indicated [here](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#running-the-tests)

The error messages below should shod up

```
  /Applications/Visual Studio Code.app/Contents/MacOS/Electron --debugBrkPluginHost=49298 --debugId=4c2f3580-bb45-4792-afe3-c16843539266 --extensionDevelopmentPath=/Users/tristian/Repositories/github.com/Microsoft/vscode-go --extensionTestsPath=/Users/tristian/Repositories/github.com/Microsoft/vscode-go/out/test 

  Go Extension Tests
Activating extension 'Gruntfuggly.todo-tree' failed: Cannot read property 'map' of undefined.
Activating extension `Gruntfuggly.todo-tree` failed:  Cannot read property 'map' of undefined
Here is the error stack:  TypeError: Cannot read property 'map' of undefined
    at addWorkspaceFolders (/Users/tristian/.vscode/extensions/gruntfuggly.todo-tree-0.0.98/tree.js:197:22)
    at TreeNodeProvider.clear (/Users/tristian/.vscode/extensions/gruntfuggly.todo-tree-0.0.98/tree.js:336:9)
    at rebuild (/Users/tristian/.vscode/extensions/gruntfuggly.todo-tree-0.0.98/extension.js:252:18)
    at register (/Users/tristian/.vscode/extensions/gruntfuggly.todo-tree-0.0.98/extension.js:649:9)
    at activate (/Users/tristian/.vscode/extensions/gruntfuggly.todo-tree-0.0.98/extension.js:657:5)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:626:411)
    at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:626:90)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:625:263
    at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:78:971)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:277)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:100)
    at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:559)
    at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:1011)
    at n.Class.derive.join.i.forEach.$.then.o.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:205)
    at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:78:971)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:277)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:100)
    at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:559)
    at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:1011)
    at n.Class.derive.join.i.forEach.$.then.o.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:205)
    at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:78:971)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:277)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:100)
    at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:559)
    at e.resolveOk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:444:313)
    at t._receiveReply (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:117)
    at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:638:425)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:926
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:138
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:213)
    at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:432)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by Gruntfuggly** [comment]
Thanks - I've just uploaded a new version which should fix it.
